import type { FamilyStudioSettings, FamilyMember } from '../types';

export const FAMILY_SCENES = [
    'studio_white',
    'studio_gray',
    'studio_warm',
    'living_room',
    'park_picnic',
    'beach_sunset',
    'flower_garden',
    'tet_holiday',
    'christmas',
    'cozy_cafe',
    'rooftop_garden',
    'amusement_park',
    'sports_stadium',
    'ancient_town',
    'mountain_landscape',
    'forest_camping',
    'clear_stream',
    'lavender_field',
    'terraced_fields',
    'autumn_leaves',
    'luxury_yacht',
    'city_rooftop',
    'resort_pool',
    'farm_setting',
    'vintage_style',
    'ha_long_bay',
    'golden_rice_field',
    'da_lat_pine_forest',
    'underwater_aquarium',
    'on_the_moon',
    'fairytale_castle',
    'cyberpunk_city',
    'luxury_library',
    'art_museum',
    'hot_air_balloon',
    'sky_lantern_festival',
    'sapa_town',
    'hanoi_old_quarter',
    'hoan_kiem_lake',
    'trang_an_ninh_binh',
    'hue_imperial_city',
    'golden_bridge_danang',
    'nha_trang_beach',
    'dalat_flower_garden',
    'mui_ne_sand_dunes',
    'mekong_delta',
    'eiffel_tower_paris',
    'times_square_nyc',
    'great_wall_china',
    'pyramids_egypt',
    'santorini_greece',
    'ski_resort',
    'concert_stage',
    'art_gallery_opening',
    'baking_in_kitchen',
    'reading_by_fireplace',
    'wizarding_school_library',
    'on_a_cloud',
    'dinosaur_park',
    'spaceship_interior',
    'underwater_city',
    'ha_giang_loop',
    'son_doong_cave',
    'my_khe_beach_danang',
    'cai_rang_floating_market',
    'temple_of_literature',
    'hanoi_opera_house',
    'ponagar_tower',
    'sao_beach_phu_quoc',
    'northern_ancient_house',
    'tet_feast_table',
    'red_carpet_event',
    'on_the_golf_course',
    'royal_palace',
    'hollywood_film_set',
    'steampunk_world',
];

export const FAMILY_OUTFITS = [
    'formal_vest',
    'business_suits',
    'smart_casual',
    'turtleneck_and_blazer',
    'smart_trench_coats',
    'casual_jeans',
    'matching_tshirts',
    'patriotic_tshirt_shorts',
    'patriotic_polo_khaki',
    'matching_pajamas',
    'luxury_silk_pajamas',
    'matching_sweaters',
    'matching_sportswear',
    'traditional_ao_dai',
    'vietnam_flag_ao_dai',
    'vietnam_sportswear',
    'traditional_ethnic',
    'beachwear',
    'winter_coats',
    'bohemian_style',
    'historical_costumes',
    'retro_vietnam',
    'school_uniform',
    'medical_attire',
    'graduation_gowns',
    'denim_leather',
    'halloween_costumes',
    'mid_autumn_costumes',
    'royal_family_attire',
    'superhero_family',
    'fairytale_costumes',
    'astronaut_costumes',
    'cooking_together',
    'gardening_outfits',
];

export const FAMILY_POSES = [
    'formal_standing',
    'casual_sitting',
    'playful_interaction',
    'walking_together',
    'group_hug',
];

export const DEFAULT_FAMILY_STUDIO_SETTINGS: FamilyStudioSettings = {
    members: [
        { id: `member_${Date.now()}_1`, photo: null, age: '' },
        { id: `member_${Date.now()}_2`, photo: null, age: '' },
    ],
    scene: 'Studio (Nền trắng)',
    outfit: 'Lịch sự (Sơ mi & Váy)',
    pose: 'Đứng trang trọng',
    customPrompt: '',
    aspectRatio: '4:3',
};