




export default {
    "magicEraser": {
        "title": "Magic Eraser Studio",
        "subtitle": "Remove objects & watermarks from Images & Videos with AI",
        "history": "Recent Edits",
        "vipNote": "Advanced video watermark removal is exclusive to VIP members.",
        "videoInfo": "Video Information",
        "format": "Video Format",
        "downloadMain": "Download Video",
        "aiPrompt": "AI Prompt",
        "tabs": {
            "image": "Image Remover",
            "video": "Video Remover"
        },
        "image": {
            "uploadTitle": "Upload Image",
            "uploadDesc": "Supports PNG, JPG, WEBP. Max 15MB.",
            "compareTitle": "Compare Before / After",
            "resultTitle": "Result",
            "process": "Remove Watermark",
            "download": "Download"
        },
        "video": {
            "uploadTitle": "Video Source",
            "inputType": {
                "file": "Upload File",
                "url": "Paste Link"
            },
            "uploadDesc": "Supports MP4, MOV. Max 50MB.",
            "placeholders": {
                "general": "Paste direct video link (MP4, MOV...)",
                "veo": "Paste Veo video link...",
                "sora": "Paste Sora video link..."
            },
            "urlDescGeneral": "System will auto-download from direct link.",
            "urlDescVeo": "Supports links from Veo Generator or Google Drive.",
            "urlDescSora": "Supports links from Sora or OpenAI.",
            "sourceLabel": "Video Source (For AI Optimization)",
            "sourceOptions": {
                "general": "General Video",
                "veo": "Generated by Veo 3.1",
                "sora": "Generated by Sora 2"
            },
            "process": "Process Video (VIP)",
            "processLink": "Download & Process Video",
            "download": "Download Clean Video"
        },
        "status": {
            "uploading": "Uploading...",
            "downloading_url": "Downloading from URL...",
            "analyzing": "Analyzing frames...",
            "processing": "AI is analyzing and processing...",
            "cleaning": "Removing watermark...",
            "finalizing": "Finalizing...",
            "success": "Processing successful!"
        },
        "errors": {
            "noFile": "Please upload a file or paste a link.",
            "invalidUrl": "Invalid URL.",
            "fileTooLarge": "File size is too large.",
            "imageFailed": "Image processing failed.",
            "videoFailed": "Original video source not found. Please check the link."
        }
    }
}
