export default {
    "legal": {
        "privacy": {
            "title": "Chính sách Bảo mật",
            "content": "Chào mừng bạn đến với PHOTO TOOL PRO. Chúng tôi cam kết bảo vệ quyền riêng tư của bạn. Chính sách Bảo mật này giải thích cách chúng tôi thu thập, sử dụng, tiết lộ và bảo vệ thông tin của bạn khi bạn sử dụng ứng dụng của chúng tôi.\n\n1. Thông tin chúng tôi thu thập\n\na) Thông tin Cá nhân:\n- Thông tin Tài khoản: Khi bạn đăng ký, chúng tôi có thể thu thập tên người dùng của bạn. Chúng tôi không yêu cầu email hoặc tên thật.\n- Thông tin Liên hệ: Nếu bạn liên hệ với chúng tôi để được hỗ trợ, chúng tôi sẽ thu thập chi tiết liên hệ và nội dung cuộc trao đổi của bạn.\n\nb) Thông tin Phi cá nhân:\n- Dữ liệu Sử dụng: Chúng tôi có thể thu thập thông tin về cách bạn sử dụng ứng dụng, chẳng hạn như các tính năng được sử dụng và tần suất sử dụng, để cải thiện dịch vụ của mình.\n\nc) Dữ liệu Hình ảnh:\n- Ảnh Tải lên: Chúng tôi xử lý tạm thời các hình ảnh bạn tải lên để cung cấp các dịch vụ chỉnh sửa bằng AI. Chúng tôi không yêu cầu bất kỳ quyền sở hữu nào đối với hình ảnh của bạn.\n- Lưu trữ Ảnh: Để thuận tiện cho bạn, các ảnh đã tạo có thể được lưu vào bộ nhớ đệm tạm thời. Tuy nhiên, ảnh gốc đã tải lên KHÔNG được lưu trữ trên máy chủ của chúng tôi sau khi phiên chỉnh sửa hoàn tất. Chúng tôi không chịu trách nhiệm lưu trữ dữ liệu của bạn.\n\n2. Cách chúng tôi sử dụng thông tin của bạn\n\nChúng tôi sử dụng thông tin thu thập được để:\n- Cung cấp, vận hành và duy trì ứng dụng của chúng tôi.\n- Cải thiện, cá nhân hóa và mở rộng dịch vụ của chúng tôi.\n- Hiểu và phân tích cách bạn sử dụng ứng dụng của chúng tôi.\n- Liên lạc với bạn để cung cấp dịch vụ khách hàng và hỗ trợ.\n- Ngăn chặn các hoạt động gian lận.\n\n3. Chia sẻ thông tin của bạn\n\nChúng tôi không bán, trao đổi hoặc chuyển giao thông tin nhận dạng cá nhân của bạn cho các bên bên ngoài. Điều này không bao gồm các bên thứ ba đáng tin cậy hỗ trợ chúng tôi vận hành ứng dụng, miễn là các bên đó đồng ý giữ bí mật thông tin này.\n\nCụ thể, hình ảnh của bạn được gửi đến Google Gemini API để xử lý. Việc bạn sử dụng dịch vụ của chúng tôi tuân theo Chính sách Bảo mật của Google.\n\n4. An toàn thông tin của bạn\n\nChúng tôi sử dụng các biện pháp an ninh hành chính, kỹ thuật và vật lý để giúp bảo vệ thông tin cá nhân của bạn. Mặc dù chúng tôi đã thực hiện các bước hợp lý để bảo mật thông tin cá nhân bạn cung cấp cho chúng tôi, xin lưu ý rằng bất chấp những nỗ lực của chúng tôi, không có biện pháp bảo mật nào là hoàn hảo hoặc không thể xuyên thủng.\n\n5. Quyền của bạn\n\nBạn có quyền truy cập, cập nhật hoặc xóa thông tin tài khoản của mình bất kỳ lúc nào. Bạn chịu trách nhiệm tải xuống và lưu bất kỳ hình ảnh nào bạn muốn giữ lại.\n\n6. Thay đổi Chính sách này\n\nChúng tôi có thể cập nhật Chính sách Bảo mật này theo thời gian. Chúng tôi sẽ thông báo cho bạn về bất kỳ thay đổi nào bằng cách đăng Chính sách Bảo mật mới trên trang này.\n\n7. Liên hệ với chúng tôi\n\nNếu bạn có bất kỳ câu hỏi nào về Chính sách Bảo mật này, vui lòng liên hệ với chúng tôi qua các kênh hỗ trợ của chúng tôi."
        },
        "terms": {
            "title": "Điều khoản Dịch vụ",
            "content": "Vui lòng đọc kỹ các Điều khoản Dịch vụ này trước khi sử dụng ứng dụng PHOTO TOOL PRO.\n\n1. Đồng ý với Điều khoản\n\nBằng cách sử dụng ứng dụng của chúng tôi, bạn đồng ý bị ràng buộc bởi các Điều khoản này. Nếu bạn không đồng ý với các Điều khoản này, không sử dụng ứng dụng.\n\n2. Tài khoản Người dùng\n\nBạn chịu trách nhiệm bảo vệ tài khoản của mình và cho bất kỳ hoạt động hoặc hành động nào trong tài khoản của bạn. Bạn đồng ý không tiết lộ mật khẩu của mình cho bất kỳ bên thứ ba nào.\n\n3. Nội dung Người dùng\n\n- Quyền sở hữu: Bạn giữ toàn quyền sở hữu đối với các hình ảnh gốc bạn tải lên và bất kỳ hình ảnh nào được tạo ra bởi AI dựa trên các tệp tải lên của bạn (\"Nội dung được tạo\"). Chúng tôi không yêu cầu bất kỳ quyền sở hữu nào đối với nội dung của bạn.\n- Trách nhiệm: Bạn hoàn toàn chịu trách nhiệm về nội dung bạn tải lên. Bạn đồng ý không tải lên bất kỳ nội dung nào là bất hợp pháp, xúc phạm hoặc vi phạm quyền của người khác (ví dụ: bản quyền, quyền riêng tư).\n\n4. Hành vi bị cấm\n\nBạn đồng ý không sử dụng ứng dụng để:\n- Tạo nội dung khiêu dâm, bạo lực hoặc thù hận.\n- Vi phạm quyền sở hữu trí tuệ của người khác.\n- Tham gia vào bất kỳ hoạt động nào là bất hợp pháp hoặc gian lận.\n- Cố gắng đảo ngược kỹ thuật hoặc làm gián đoạn dịch vụ.\n\nChúng tôi có quyền chấm dứt các tài khoản vi phạm các quy tắc này.\n\n5. Tính sẵn có của Dịch vụ\n\nChúng tôi sẽ cố gắng giữ cho dịch vụ hoạt động. Tuy nhiên, chúng tôi không chịu trách nhiệm cho bất kỳ thời gian chết hoặc mất dữ liệu nào. Dịch vụ được cung cấp \"nguyên trạng\" mà không có bất kỳ bảo đảm nào.\n\n6. Giới hạn Trách nhiệm\n\nTrong mọi trường hợp, PHOTO TOOL PRO, cũng như giám đốc hoặc nhân viên của nó, sẽ không chịu trách nhiệm cho bất kỳ thiệt hại gián tiếp, ngẫu nhiên, đặc biệt, do hậu quả hoặc trừng phạt nào phát sinh từ việc bạn sử dụng dịch vụ.\n\n7. Thay đổi Điều khoản\n\nChúng tôi có thể sửa đổi các Điều khoản này bất kỳ lúc nào. Chúng tôi sẽ thông báo về các thay đổi bằng cách đăng các Điều khoản đã cập nhật trong ứng dụng.\n\n8. Liên hệ với chúng tôi\n\nNếu bạn có bất kỳ câu hỏi nào về các Điều khoản này, vui lòng liên hệ với chúng tôi."
        }
    }
}
